### ISSUE TITLE
what will this be?

### ISSUE THREAD

**Issue by CombatPompano81** [CranyBrainly/Homemade-Dashboard-v2#1]
is this for the chill cavern discord server or for something else?

**Comment by CranyBrainly** [comment]
Nope, everything concerning the Chill Network is private for security purposes.

**Comment by CombatPompano81** [comment]
alrightio

do devs (like me if i were to be accepted) have access to the project repos?

**Comment by CranyBrainly** [comment]
1) Yes. Once you can be trusted.
2) If there are any other things you want to ask, please contact via the Discord Server or via DMs.

**Comment by CombatPompano81** [comment]
lol

yup, will do. just wanted to see if this was actually something of use :)
